Fred2/CleavagePrediction/External.py
Fred2/Core/Base.py
Fred2/EpitopePrediction/External.py
Fred2/test/external/TestExternalEpitopePrediction.py

- Checking accessibility of external binaries
- Checking external version with internal version

Cherry Picking pull request #31

---

Fred2/Core/Generator.py
Fred2/Core/Transcript.py
Fred2/test/TestProtein.py

- removed translate method from Transcript and
- added a generator function ```generate_protein_from_transcript```

Transcript.translate() refactoring

---

Fred2/CleavagePrediction/External.py
Fred2/Core/Base.py
Fred2/EpitopePrediction/External.py

abstracted input preparation of peptide sequence for external tools

Abstraction of input preparation for external tools

---

Fred2/TAPPrediction/PSSM.py
Fred2/test/TestTAPPrediction.py

Extended SMMTAP to arbitrary peptide length as described in Peters et al.

Extention SMMTAP 

---

Fred2/EpitopeAssembly/EpitopeAssembly.py
Fred2/EpitopeAssembly/MosaicVaccine.py
Fred2/EpitopeSelection/OptiTope.py
Fred2/test/TestEpitopeAssembly.py
Fred2/test/TestOptiTope.py
setup.py

Changed pyomo dependent code from Pyomo 4.0 to Pyomo 4.2 API
Fix of Issue #46

Fix/pyomo 4.2

---

Fred2/Core/Generator.py
Fred2/test/TestGenerator.py
Fred2/test/VariantsForTesting.py

- Changed generator function to work with generators as input
- Added tests for generate_peptides_from_variants, generate_proteins_from_transcripts

[FIX] Fixed bugs in generate_peptides_from_protein

---

README.rst

- Setuptools can read markdown and needs reStruc README

[FIX] setuptools needs reStruc

---

Fred2/Core/Result.py

with visual example of data frame structure

[DOC] Results objects documented 

---

Fred2/Core/Generator.py

[FEATURE] generate_peptides_from_proteins filters now peptides 

---

Fred2/EpitopeAssembly/EpitopeAssembly.py

- to 1-log50k(10^score)
- reduced precision of approximation to 4 fractional digits

[INTERNAL] changed score normalisation of SMM 

---

Fred2/EpitopeAssembly/EpitopeAssembly.py

if branch for smm etc was never reached

SMM transformation branch now reachable

---

Fred2/EpitopePrediction/PSSM.py

Implemented Calis Immunogenicity propensity score

Added Calis Immunogenicity propencity score

---

Fred2/Core/Variant.py
Fred2/IO/FileReader.py

MutationSyntax also stores GeneIDs
ANNOVAR reader is adjusted accordingly

[INTERNAL] GeneID annotation in MutationSyntax

---

Fred2/Core/Allele.py
Fred2/test/TestAllele.py
Fred2/test/external/TestExternalEpitopePrediction.py
Fred2/test/external/TestExternalHLATyping.py

Added AlleleFactory-metaclass that allows Allele object to initialize a CombinedAllele-object if appropriate (i.e. if it's given a combined allele name DQA-DQB)

[Internal] Allele factory

---

Fred2/CleavagePrediction/External.py
Fred2/EpitopeAssembly/EpitopeAssembly.py
Fred2/EpitopeSelection/OptiTope.py
Fred2/IO/MartsAdapter.py

- SpacerDesign: fixed bug that appeared if beta!=0
- OptiTope: fixed bug that appeared if antigen_covera_constraint was activated
- MartsAdapter: Updated get_variant_id_from_protein_id function to fit keywords of ENSAMBL DB
- Fixed bug in CleavageSitePRediction.External that appeared if only peptides were given as input

[FIX] Minor bug fixes

---

Fred2/CleavagePrediction/External.py
Fred2/EpitopePrediction/PSSM.py
Fred2/EpitopePrediction/SVM.py
Fred2/TAPPrediction/SVM.py
Fred2/test/TestTAPPrediction.py

- peptide chunking fully implemented

[INTERNAL] peptide chunking (extended)

---

Fred2/EpitopeAssembly/EpitopeAssembly.py
Fred2/test/TestSpacerDesign.py

- an Error that is caused by an import of a PSSM matrix for an unsupported allele and length combination
- Added also Unittests that checks this bug

[FIX] Unsupported PSSM import EpitopeAssemblyWithSpacers

---

Fred2/CleavagePrediction/External.py

fixes two small issues that did not allow handed commands an…

[HOTFIX] for NetChop

---

README.md

Adds conda flag to indicate that FRED is now conda installable thanks to @apeltzer

[UPDATE] Conda installable

---

Fred2/IO/MartsAdapter.py
README.md
setup.py

Change mysql dependency to PyMySQL

---

Fred2/EpitopePrediction/ANN.py

Copy of https://github.com/FRED-2/Fred2/pull/231

[FIX] ANN Predictor alleles mismatching #231
